/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7c8c9c00fc19ba13e0335d879c9e2ecb)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	SYGSHIFT_PUBLIC_APP_URL: "https://app.sygilant.us";
	SYGSHIFT_EMAIL_FROM: "scheduling@sygilant.us";
	SYGSHIFT_EMAIL_FROM_NAME: "SygShift";
	SYGSHIFT_BLOCKED_EMAIL_DOMAINS: "guardianshipsecurity.net";
	SUPABASE_URL: "https://eqkdfrbwtioiqtjsyglg.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_-uU9fD3XIeZ58r815-fl_Q_g4IIRPQ5";
	VITE_SUPABASE_URL: "https://eqkdfrbwtioiqtjsyglg.supabase.co";
	VITE_SUPABASE_PUBLISHABLE_KEY: "sb_publishable_-uU9fD3XIeZ58r815-fl_Q_g4IIRPQ5";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
