import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'

const fixture = 'http://127.0.0.1:4185/tests/fixtures/support-ui.html'
async function openFixture(page: Page, query = '') {
  await page.route('**/*', (route) => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
  await page.goto(fixture + query)
}
async function fillDetails(page: Page) {
  await page.getByLabel('Schedule or assigned shift').check()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Specific issue').selectOption('Missing shift')
  await page.getByLabel('Subject', { exact: true }).fill('Missing assignment for next week')
  await page.getByLabel('Complete description').fill('My assignment for next week is missing. I refreshed the schedule but still cannot see it.')
}
async function verifyControls(page: Page) {
  for (const control of await page.locator('.support-form input:not([type=checkbox]):not([type=radio]), .support-form select, .support-form textarea, .support-reply textarea, .support-management select').all()) {
    const style = await control.evaluate((element) => ({ radius: parseFloat(getComputedStyle(element).borderRadius), height: element.getBoundingClientRect().height, font: getComputedStyle(element).fontFamily, padding: parseFloat(getComputedStyle(element).paddingLeft) }))
    expect(style.radius).toBeGreaterThanOrEqual(10)
    expect(style.height).toBeGreaterThanOrEqual(44)
    expect(style.padding).toBeGreaterThanOrEqual(12)
    expect(style.font).not.toMatch(/monospace|courier/i)
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  for (const progress of await page.locator('.support-progress').all()) expect((await progress.boundingBox())!.height).toBeLessThanOrEqual(110)
  for (const hidden of await page.locator('.support-progress .visually-hidden').all()) expect((await hidden.boundingBox())!.width).toBeLessThanOrEqual(1)
}

for (const theme of ['light', 'dark']) {
  test(`real support intake progresses with padded controls in ${theme}`, async ({ page }, testInfo) => {
    await openFixture(page)
    await page.evaluate((value) => { document.documentElement.dataset.theme = value; document.documentElement.style.colorScheme = value }, theme)
    const dialog = page.getByRole('dialog')
    await expect(dialog.locator('[aria-current=step]')).toContainText('Topic')
    await expect(page.getByRole('button', { name: 'Continue' })).toBeDisabled()
    expect(await page.locator('.support-form').evaluate((el) => parseFloat(getComputedStyle(el).paddingLeft))).toBeGreaterThanOrEqual(16)
    await page.screenshot({ path: testInfo.outputPath(`topic-${theme}.png`), fullPage: true })
    await fillDetails(page)
    await expect(dialog.locator('[aria-current=step]')).toContainText('Details')
    await expect(dialog.locator('.support-progress .is-complete')).toHaveCount(1)
    await verifyControls(page)
    await page.screenshot({ path: testInfo.outputPath(`details-${theme}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Continue' }).click()
    await expect(dialog.locator('[aria-current=step]')).toContainText('Impact')
    await page.getByLabel('My pay may be affected').check()
    await verifyControls(page)
    await page.screenshot({ path: testInfo.outputPath(`impact-${theme}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Continue' }).click()
    await expect(dialog.locator('[aria-current=step]')).toContainText('Review')
    await expect(page.getByText('Missing assignment for next week')).toBeVisible()
    await page.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(page.getByLabel('My pay may be affected')).toBeChecked()
    await page.getByRole('button', { name: 'Continue' }).click()
    const audit = await new AxeBuilder({ page }).include('.modal-dialog--support').analyze()
    expect(audit.violations).toEqual([])
    await page.screenshot({ path: testInfo.outputPath(`review-${theme}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Submit Support Ticket' }).click()
    await expect(page.locator('button[type=submit]')).toBeDisabled()
    await expect(page.getByRole('heading', { name: 'Support ticket submitted' })).toBeVisible()
    expect(await page.locator('.support-confirmation').evaluate((el) => parseFloat(getComputedStyle(el).paddingLeft))).toBeGreaterThanOrEqual(16)
    await page.screenshot({ path: testInfo.outputPath(`confirmation-${theme}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Done', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await page.getByRole('button', { name: 'Need Help?' }).click()
    await expect(page.locator('[aria-current=step]')).toContainText('Topic')
  })

  test(`ticket lifecycle and conversational replies in ${theme}`, async ({ page }, testInfo) => {
    await openFixture(page, '?workspace')
    await page.evaluate((value) => { document.documentElement.dataset.theme = value; document.documentElement.style.colorScheme = value }, theme)
    const management = page.getByRole('region', { name: 'Ticket management' })
    await expect(management).toBeVisible()
    await expect(management.getByRole('combobox', { name: 'Status', exact: true }).locator('option')).toHaveCount(6)
    await expect(management.getByRole('combobox', { name: 'Status', exact: true }).locator('option[value=closed]')).toHaveCount(0)
    await verifyControls(page)
    await page.getByRole('textbox', { name: 'Reply to ticket', exact: true }).fill('Thanks for the details, Alex. I am checking your assignment now.')
    await page.getByRole('button', { name: 'Send reply', exact: true }).click()
    await expect(page.locator('.support-message')).toContainText('Thanks for the details')
    await expect(page.locator('.support-lifecycle [aria-current=step]')).toContainText('In progress')
    await page.getByLabel('Add as an internal note').check()
    await page.getByLabel('Internal note', { exact: true }).fill('A staff-only follow-up note.')
    await page.getByRole('button', { name: 'Add internal note', exact: true }).click()
    await expect(page.getByText('Internal note added. No email was queued.')).toBeVisible()
    await management.getByRole('combobox', { name: 'Status', exact: true }).selectOption('waiting_on_employee')
    await expect(page.getByText('Waiting for the employee to reply.')).toBeVisible()
    await verifyControls(page)
    expect((await page.locator('.communications-pagination--compact').boundingBox())!.height).toBeLessThanOrEqual(105)
    await page.emulateMedia({ reducedMotion: 'reduce' })
    expect(await page.locator('.support-lifecycle .is-current .support-progress__step').evaluate((el) => getComputedStyle(el).animationName)).toBe('none')
    await page.screenshot({ path: testInfo.outputPath(`conversation-${theme}.png`), fullPage: true })
    await management.getByRole('combobox', { name: 'Status', exact: true }).selectOption('resolved')
    await expect(page.locator('.support-lifecycle [aria-current=step]')).toContainText('Resolved')
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  })
}

test('intake and management errors retain user work and explain failure', async ({ page }) => {
  await openFixture(page, '?error')
  await fillDetails(page)
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Submit Support Ticket' }).click()
  await expect(page.getByRole('alert')).toContainText('connection was interrupted')
  await expect(page.getByText('Missing assignment for next week')).toBeVisible()
  await page.goto(fixture + '?workspace&error')
  await page.getByRole('region', { name: 'Ticket management' }).getByRole('combobox', { name: 'Status', exact: true }).selectOption('resolved')
  await expect(page.getByRole('alert')).toContainText('Ticket change could not be saved')
  await expect(page.locator('.support-lifecycle [aria-current=step]')).toContainText('New')
  await page.getByRole('textbox', { name: 'Reply to ticket', exact: true }).fill('Keep this draft if the server is unavailable.')
  await page.getByRole('button', { name: 'Send reply', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Reply to ticket', exact: true })).toHaveValue('Keep this draft if the server is unavailable.')
  await expect(page.getByText('Reply could not be saved. Please try again.')).toBeVisible()
})
