import { expect, test } from '@playwright/test'
const fixture = `http://127.0.0.1:${4190 + Number(process.env.PLAYWRIGHT_PORT_OFFSET ?? 0)}/tests/fixtures/sphere-ui.html`
test('creates a group using the real rounded form and sends a message', async ({ page }) => {
  await page.goto(`${fixture}?scope=${crypto.randomUUID()}`)
  await page.getByRole('button', { name: 'New message', exact: true }).click()
  await page.getByLabel('Conversation type').selectOption('group')
  await page.getByLabel('Group name').fill('Evening handoff')
  await page.getByRole('checkbox', { name: /Devon Ruiz/ }).check()
  await page.getByRole('button', { name: 'Create conversation', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Evening handoff', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('Ready for tonight’s handoff.')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.locator('.sphere-message__body').filter({ hasText: 'Ready for tonight’s handoff.' })).toBeVisible()
})
test('keeps drafts over reload, retains a failed send and retries successfully', async ({ page }) => {
  await page.goto(`${fixture}?scope=${crypto.randomUUID()}`)
  const input = page.getByRole('textbox', { name: 'Write a message', exact: true })
  await input.fill('Do not lose this handoff draft')
  await page.reload()
  await expect(input).toHaveValue('Do not lose this handoff draft')
  await page.getByRole('button', { name: 'Simulate one failed send' }).click()
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Connection interrupted')
  await expect(input).toHaveValue('Do not lose this handoff draft')
  await page.getByRole('button', { name: 'Retry send', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(page.locator('.sphere-message__body')).toHaveCount(1)
})
test('opens an actual thread, sends a reply, saves and searches it', async ({ page }) => {
  await page.goto(`${fixture}?scope=${crypto.randomUUID()}`)
  await page.getByRole('textbox', { name: 'Write a message', exact: true }).fill('Please confirm coverage')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByRole('button', { name: 'Reply', exact: true }).click()
  await page.getByRole('textbox', { name: 'Write a thread reply', exact: true }).fill('Coverage confirmed')
  await page.locator('.sphere-thread').getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.locator('.sphere-thread .sphere-message__body').filter({ hasText: 'Coverage confirmed' })).toBeVisible()
  await page.locator('.sphere-thread article').filter({ hasText: 'Coverage confirmed' }).getByRole('button', { name: 'Save message', exact: true }).click()
  await page.getByRole('button', { name: 'Close thread' }).click()
  const back = page.getByRole('button', { name: 'Back to conversations' })
  if (await back.isVisible()) await back.click()
  await page.getByRole('button', { name: 'Saved', exact: true }).click()
  await expect(page.locator('.sphere-result').filter({ hasText: 'Coverage confirmed' })).toBeVisible()
})
test('live message reaches the other account without refresh and has a separate launcher badge', async ({ context }) => {
  const scope = crypto.randomUUID(); const first = await context.newPage(); const second = await context.newPage()
  await first.goto(`${fixture}?scope=${scope}`); await second.goto(`${fixture}?scope=${scope}&second&home`)
  await expect(first.getByRole('textbox', { name: 'Write a message', exact: true })).toBeVisible()
  await first.getByRole('textbox', { name: 'Write a message', exact: true }).fill('Live two-account handoff')
  await first.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(second.locator('.sphere-launcher .sphere-badge')).toHaveText('1')
  await expect(second.locator('.sphere-toast')).toContainText('SygSphere')
  await second.locator('.sphere-toast a').click()
  await expect(second.locator('.sphere-message__body')).toContainText('Live two-account handoff')
})
for (const theme of ['light', 'dark']) test(`comfortable ${theme} controls and no horizontal overflow`, async ({ page }) => {
  await page.goto(`${fixture}?scope=${crypto.randomUUID()}&theme=${theme}`)
  await expect(page.getByRole('textbox', { name: 'Write a message', exact: true })).toBeVisible()
  const result = await page.locator('.sphere-workspace').evaluate((node) => ({ overflow: node.scrollWidth - node.clientWidth, font: getComputedStyle(node.querySelector('textarea')!).fontFamily, radius: getComputedStyle(node.querySelector('textarea')!).borderRadius }))
  expect(result.overflow).toBeLessThanOrEqual(1); expect(result.font).not.toContain('monospace'); expect(parseFloat(result.radius)).toBeGreaterThanOrEqual(8)
  await page.screenshot({ path: `test-results/sygsphere-${theme}-${test.info().project.name}.png`, fullPage: true })
})
