import { type FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, FileCheck2, FileCog, FileSignature, FileStack, Plus, Send, ShieldAlert, ShieldCheck, Users, Workflow, XCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ModalDialog } from './ModalDialog'
import { DataStatePanel } from './DataStatePanel'
import { HrDocumentLibrary } from './HrDocumentLibrary'
import {
  addDocumentTemplateField,
  createDocumentPolicy,
  createDocumentTemplate,
  createSignatureEnvelope,
  getDocumentStudioWorkspace,
  publishDocumentTemplate,
  sendSignatureEnvelope,
  voidSignatureEnvelope,
  type DocumentStudioEnvelope,
  type DocumentStudioTemplate,
} from '../data/documentStudio'
import type { HrDocumentWorkspace } from '../data/hrDocuments'
import { formatOperationalDateTime } from '../lib/time'

type StudioTab = 'overview' | 'library' | 'templates' | 'signatures' | 'policies' | 'processing'

function statusLabel(value: string) { return value.replaceAll('_', ' ') }

export function DocumentStudioDashboard({ documents }: { documents?: HrDocumentWorkspace }) {
  const client = useQueryClient()
  const [tab, setTab] = useState<StudioTab>('overview')
  const [modal, setModal] = useState<'policy' | 'template' | 'envelope' | null>(null)
  const [fieldTarget, setFieldTarget] = useState<DocumentStudioTemplate | null>(null)
  const query = useQuery({ queryFn: () => getDocumentStudioWorkspace(), queryKey: ['document-studio'] })
  const refresh = () => client.invalidateQueries({ queryKey: ['document-studio'] })
  if (query.isPending) return <DataStatePanel icon={FileStack} title="Loading Document Studio"><p>Checking protected workspace permissions and release controls.</p></DataStatePanel>
  if (query.isError) return <DataStatePanel icon={AlertTriangle} tone="error" title="Document Studio unavailable"><p>{query.error instanceof Error ? query.error.message : 'The workspace could not be loaded.'}</p></DataStatePanel>
  const data = query.data
  return (
    <section className="document-studio">
      <div className={`document-studio__release ${data.releaseState.documentPipeline && data.releaseState.workspace ? 'ready' : 'held'}`}>
        {data.releaseState.documentPipeline && data.releaseState.workspace ? <ShieldCheck size={22}/> : <ShieldAlert size={22}/>}<div><strong>{data.releaseState.documentPipeline && data.releaseState.workspace ? 'Protected workspace released' : 'Security release held'}</strong><span>{data.releaseState.documentPipeline && data.releaseState.workspace ? 'Quarantine, scan, version, access, and audit controls are active.' : 'The system is installed, but document uploads remain closed until the scanner canary and recovery drill pass.'}</span></div>
      </div>
      <div className="document-studio__metrics">
        <article><FileStack/><span>Documents</span><strong>{data.summary.documents}</strong></article>
        <article><FileCog/><span>Templates</span><strong>{data.summary.templates}</strong></article>
        <article><Workflow/><span>Awaiting action</span><strong>{data.summary.awaitingAction}</strong></article>
        <article><CheckCircle2/><span>Completed</span><strong>{data.summary.completed}</strong></article>
        <article className={data.summary.exceptions ? 'attention' : ''}><AlertTriangle/><span>Exceptions</span><strong>{data.summary.exceptions}</strong></article>
      </div>
      <div className="document-studio__tabs" role="tablist" aria-label="Document Studio sections">
        {(['overview','library','templates','signatures','policies','processing'] as StudioTab[]).map((item) => <button aria-selected={tab===item} className={tab===item?'active':''} key={item} onClick={()=>setTab(item)} role="tab" type="button">{item[0].toUpperCase()+item.slice(1)}</button>)}
      </div>
      {tab==='overview' ? <div className="document-studio__overview"><article><FileCheck2/><div><h3>One canonical record</h3><p>Documents keep immutable versions and link to employee, client, site, post, shift, patrol, and workflow records without copying the file.</p></div></article><article><FileSignature/><div><h3>Evidence-backed signatures</h3><p>Recipients, routing, consent, authentication, source checksum, final PDF, and audit certificate remain one protected chain.</p></div></article><article><Users/><div><h3>Employee self-service</h3><p>Assigned actions appear in <Link to="/my-documents">My Documents</Link> with secure preview, correction, decline, and completion controls.</p></div></article></div> : null}
      {tab==='library' ? <HrDocumentLibrary mode="studio"/> : null}
      {tab==='templates' ? <StudioTemplates data={data.templates} onAddField={setFieldTarget} onCreate={()=>setModal('template')} onRefresh={refresh} permitted={data.permissions.canManageTemplates && Boolean(documents)} /> : null}
      {tab==='signatures' ? <StudioEnvelopes data={data.envelopes} onCreate={()=>setModal('envelope')} onRefresh={refresh} permitted={data.permissions.canRequestSignatures} released={data.releaseState.signatures} /> : null}
      {tab==='policies' ? <StudioPolicies data={data.policies} onCreate={()=>setModal('policy')} permitted={data.permissions.canManagePolicies} /> : null}
      {tab==='processing' ? <div className="document-studio__list">{data.processing.length ? data.processing.map((job)=><article key={job.id}><div><strong>{job.documentTitle}</strong><span>{statusLabel(job.jobType)} · attempt {job.attemptCount}</span></div><span className={`document-studio__status is-${job.status}`}>{statusLabel(job.status)}</span>{job.lastErrorCode?<small>{job.lastErrorCode}</small>:null}</article>):<div className="document-studio__empty"><CheckCircle2/><strong>No processing exceptions</strong><span>Background document work is clear.</span></div>}</div> : null}
      {modal==='policy' ? <PolicyModal onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);await refresh()}} />:null}
      {modal==='template' && documents ? <TemplateModal documents={documents} policies={data.policies} onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);await refresh()}} />:null}
      {modal==='envelope' && documents ? <EnvelopeModal documents={documents} policies={data.policies} templates={data.templates} onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);await refresh()}} />:null}
      {fieldTarget ? <TemplateFieldModal template={fieldTarget} onClose={()=>setFieldTarget(null)} onSaved={async()=>{setFieldTarget(null);await refresh()}} />:null}
    </section>
  )
}

function StudioTemplates({data,onAddField,onCreate,onRefresh,permitted}:{data:DocumentStudioTemplate[];onAddField:(value:DocumentStudioTemplate)=>void;onCreate:()=>void;onRefresh:()=>Promise<unknown>;permitted:boolean}){
  const publish=useMutation({mutationFn:publishDocumentTemplate,onSuccess:()=>onRefresh()})
  return <div className="document-studio__section"><div className="document-studio__heading"><div><h2>Templates &amp; fields</h2><p>Versioned PDF sources with normalized field coordinates and signer-role mapping.</p></div>{permitted?<button className="primary-action" onClick={onCreate} type="button"><Plus size={17}/>New template</button>:null}</div><div className="document-studio__list">{data.length?data.map((template)=><article key={template.id}><div><strong>{template.name}</strong><span>{template.code} · {template.category} · {template.fieldCount} fields</span><small>{template.sourceDocumentTitle??'Source pending'} · {template.policyName??'Policy pending'}</small></div><span className={`document-studio__status is-${template.status}`}>{statusLabel(template.status)}</span>{permitted&&template.status==='draft'?<div className="document-studio__row-actions"><button className="secondary-button secondary-button--small" onClick={()=>onAddField(template)} type="button">Add field</button><button className="primary-action primary-action--small" disabled={publish.isPending||template.fieldCount<1} onClick={()=>publish.mutate(template.id)} type="button">Publish</button></div>:null}</article>):<div className="document-studio__empty"><FileCog/><strong>No templates yet</strong><span>Create one from a clean PDF after the protected upload pipeline is released.</span></div>}</div>{publish.isError?<p className="form-error">{publish.error instanceof Error?publish.error.message:'The template could not be published.'}</p>:null}</div>
}

function StudioEnvelopes({data,onCreate,onRefresh,permitted,released}:{data:DocumentStudioEnvelope[];onCreate:()=>void;onRefresh:()=>Promise<unknown>;permitted:boolean;released:boolean}){
  const [voiding,setVoiding]=useState<DocumentStudioEnvelope|null>(null)
  const send=useMutation({mutationFn:sendSignatureEnvelope,onSuccess:()=>onRefresh()})
  return <div className="document-studio__section"><div className="document-studio__heading"><div><h2>Signature envelopes</h2><p>Sequential or parallel routing with exact-version integrity and recipient evidence.</p></div>{permitted?<button className="primary-action" disabled={!released} onClick={onCreate} type="button"><Plus size={17}/>New envelope</button>:null}</div>{!released?<p className="document-studio__notice">Signature execution remains closed until the protected document pipeline passes release checks.</p>:null}<div className="document-studio__list">{data.length?data.map((envelope)=><article key={envelope.id}><div><strong>{envelope.title}</strong><span>{envelope.documentTitle} · {envelope.policyName}</span><small>{envelope.completedRecipientCount}/{envelope.recipientCount} complete · Created {formatOperationalDateTime(envelope.createdAt)}</small></div><span className={`document-studio__status is-${envelope.status}`}>{statusLabel(envelope.status)}</span>{permitted?<div className="document-studio__row-actions">{envelope.status==='draft'?<button className="primary-action primary-action--small" disabled={send.isPending} onClick={()=>send.mutate(envelope.id)} type="button"><Send size={15}/>Send</button>:null}{!['completed','voided','archived'].includes(envelope.status)?<button className="secondary-button secondary-button--small danger" onClick={()=>setVoiding(envelope)} type="button"><XCircle size={15}/>Void</button>:null}</div>:null}</article>):<div className="document-studio__empty"><FileSignature/><strong>No signature envelopes</strong><span>Prepared and completed signature workflows will appear here.</span></div>}</div>{send.isError?<p className="form-error">{send.error instanceof Error?send.error.message:'The envelope could not be sent.'}</p>:null}{voiding?<VoidEnvelopeModal envelope={voiding} onClose={()=>setVoiding(null)} onSaved={async()=>{setVoiding(null);await onRefresh()}}/>:null}</div>
}

function StudioPolicies({data,onCreate,permitted}:{data:Array<{id:string;name:string;code:string;versionNumber:number;category:string;jurisdiction:string;executionMethod:string;authenticationTier:string;routingMode:string;regulated:boolean;active:boolean}>;onCreate:()=>void;permitted:boolean}){
  return <div className="document-studio__section"><div className="document-studio__heading"><div><h2>Document policies</h2><p>Versioned consent, authentication, routing, jurisdiction, retention, and completion rules.</p></div>{permitted?<button className="primary-action" onClick={onCreate} type="button"><Plus size={17}/>New policy version</button>:null}</div><div className="document-studio__list">{data.length?data.map((policy)=><article key={policy.id}><div><strong>{policy.name}</strong><span>{policy.code} · version {policy.versionNumber} · {policy.category}</span><small>{policy.jurisdiction} · {statusLabel(policy.executionMethod)} · {policy.authenticationTier} authentication · {policy.routingMode}</small></div><span className={`document-studio__status ${policy.active?'is-published':'is-superseded'}`}>{policy.active?'active':'superseded'}</span></article>):<div className="document-studio__empty"><ShieldCheck/><strong>No policies yet</strong><span>Create the approved execution policy before building a signature template.</span></div>}</div></div>
}

function PolicyModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({policyCode:'EMPLOYEE_ACK',name:'Employee acknowledgment',documentCategory:'Employment document',jurisdiction:'US',executionMethod:'electronic',authenticationTier:'standard',routingMode:'sequential',consentText:'I have reviewed this document and agree to use an electronic signature or acknowledgment. I understand this electronic action is legally binding to the extent permitted by the applicable policy and law.',consentVersion:'1.0',expirationDays:'14',retentionPolicyCode:'MANUAL_REVIEW'})
  const mutation=useMutation({mutationFn:createDocumentPolicy,onSuccess:onSaved})
  const submit=(event:FormEvent)=>{event.preventDefault();mutation.mutate({...form,expirationDays:Number(form.expirationDays),electronicSignaturePermitted:true,signerRoles:['employee'],reminderSchedule:[3,7],allowsDecline:true,allowsCorrectionRequest:true,completedPdfRequired:true,auditCertificateRequired:true})}
  return <ModalDialog busy={mutation.isPending} busyLabel="Creating protected policy…" className="document-studio-modal" description="Publishing creates a new immutable policy version and retires the prior active version with the same code." onClose={onClose} title="New document policy version"><form className="document-studio-form" onSubmit={submit}><div className="form-grid"><label>Policy code<input maxLength={80} onChange={e=>setForm({...form,policyCode:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,'')})} required value={form.policyCode}/></label><label>Name<input maxLength={160} onChange={e=>setForm({...form,name:e.target.value})} required value={form.name}/></label><label>Category<input maxLength={100} onChange={e=>setForm({...form,documentCategory:e.target.value})} required value={form.documentCategory}/></label><label>Jurisdiction<input maxLength={80} onChange={e=>setForm({...form,jurisdiction:e.target.value})} required value={form.jurisdiction}/></label><label>Authentication<select onChange={e=>setForm({...form,authenticationTier:e.target.value})} value={form.authenticationTier}><option value="standard">Standard verified session</option><option value="elevated">Fresh MFA (10 minutes)</option><option value="specialized">Specialized external process</option></select></label><label>Routing<select onChange={e=>setForm({...form,routingMode:e.target.value})} value={form.routingMode}><option value="sequential">Sequential</option><option value="parallel">Parallel</option></select></label><label>Expires after (days)<input min={1} max={3650} onChange={e=>setForm({...form,expirationDays:e.target.value})} type="number" value={form.expirationDays}/></label><label className="wide">Consent statement<textarea maxLength={4000} onChange={e=>setForm({...form,consentText:e.target.value})} required rows={5} value={form.consentText}/></label></div>{mutation.isError?<p className="form-error">{mutation.error instanceof Error?mutation.error.message:'The policy could not be created.'}</p>:null}<div className="modal-actions"><button className="secondary-button" onClick={onClose} type="button">Cancel</button><button className="primary-action" type="submit">Publish policy version</button></div></form></ModalDialog>
}

function TemplateModal({documents,policies,onClose,onSaved}:{documents:HrDocumentWorkspace;policies:Array<{id:string;name:string;active:boolean}>;onClose:()=>void;onSaved:()=>void}){
  const cleanPdfs=documents.documents.filter(item=>item.version?.scanState==='clean'&&item.version.mimeType==='application/pdf')
  const [form,setForm]=useState({documentId:'',policyId:policies.find(item=>item.active)?.id??'',templateCode:'',name:'',description:'',category:'Employment document',changeReason:'Initial controlled template version.'})
  const mutation=useMutation({mutationFn:createDocumentTemplate,onSuccess:onSaved})
  return <ModalDialog busy={mutation.isPending} busyLabel="Creating template…" className="document-studio-modal" description="The source PDF and policy are pinned to this immutable template version." onClose={onClose} title="Create document template"><form className="document-studio-form" onSubmit={e=>{e.preventDefault();mutation.mutate(form)}}><div className="form-grid"><label className="wide">Clean PDF source<select onChange={e=>setForm({...form,documentId:e.target.value})} required value={form.documentId}><option value="">Choose a source document</option>{cleanPdfs.map(item=><option key={item.id} value={item.id}>{item.title} · version {item.version?.versionNumber}</option>)}</select></label><label>Template code<input onChange={e=>setForm({...form,templateCode:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,'')})} required value={form.templateCode}/></label><label>Template name<input onChange={e=>setForm({...form,name:e.target.value})} required value={form.name}/></label><label>Policy<select onChange={e=>setForm({...form,policyId:e.target.value})} required value={form.policyId}><option value="">Choose a policy</option>{policies.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Category<input onChange={e=>setForm({...form,category:e.target.value})} required value={form.category}/></label><label className="wide">Description<textarea onChange={e=>setForm({...form,description:e.target.value})} rows={2} value={form.description}/></label><label className="wide">Version reason<textarea onChange={e=>setForm({...form,changeReason:e.target.value})} required rows={2} value={form.changeReason}/></label></div>{!cleanPdfs.length?<p className="document-studio__notice">A security-reviewed PDF is required before a template can be created.</p>:null}{mutation.isError?<p className="form-error">{mutation.error instanceof Error?mutation.error.message:'The template could not be created.'}</p>:null}<div className="modal-actions"><button className="secondary-button" onClick={onClose} type="button">Cancel</button><button className="primary-action" disabled={!cleanPdfs.length} type="submit">Create draft template</button></div></form></ModalDialog>
}

function TemplateFieldModal({template,onClose,onSaved}:{template:DocumentStudioTemplate;onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({fieldKey:'',fieldType:'text',label:'',description:'',pageNumber:1,xRatio:.1,yRatio:.1,widthRatio:.3,heightRatio:.05,tabOrder:template.fieldCount+1,required:true,readOnly:false,signerRoleCode:'employee',semanticMapping:'',authoritative:false,sensitive:false,downloadable:true})
  const mutation=useMutation({mutationFn:(body:Record<string,unknown>)=>addDocumentTemplateField(template.currentVersionId!,body),onSuccess:onSaved})
  return <ModalDialog busy={mutation.isPending} busyLabel="Adding template field…" className="document-studio-modal" description="Coordinates are percentages of the PDF page, so field placement remains stable at every display size." onClose={onClose} title={`Add field to ${template.name}`}><form className="document-studio-form" onSubmit={e=>{e.preventDefault();mutation.mutate({...form,validationRules:{},options:[],conditionalRules:{}})}}><div className="form-grid"><label>Field key<input onChange={e=>setForm({...form,fieldKey:e.target.value.toLowerCase().replace(/[^a-z0-9_.-]/g,'')})} required value={form.fieldKey}/></label><label>Label<input onChange={e=>setForm({...form,label:e.target.value})} required value={form.label}/></label><label>Type<select onChange={e=>setForm({...form,fieldType:e.target.value})} value={form.fieldType}><option value="text">Text</option><option value="date">Date</option><option value="checkbox">Checkbox</option><option value="initials">Initials</option><option value="signature">Signature</option><option value="signer_date">Signer date</option><option value="acknowledgment">Acknowledgment</option></select></label><label>Signer role<input onChange={e=>setForm({...form,signerRoleCode:e.target.value})} value={form.signerRoleCode}/></label><label>Page<input min={1} onChange={e=>setForm({...form,pageNumber:Number(e.target.value)})} type="number" value={form.pageNumber}/></label><label>Tab order<input min={1} onChange={e=>setForm({...form,tabOrder:Number(e.target.value)})} type="number" value={form.tabOrder}/></label>{(['xRatio','yRatio','widthRatio','heightRatio'] as const).map(key=><label key={key}>{key.replace('Ratio',' %')}<input max={100} min={0} onChange={e=>setForm({...form,[key]:Number(e.target.value)/100})} step={1} type="number" value={Math.round(form[key]*100)}/></label>)}<label className="checkbox-row"><input checked={form.required} onChange={e=>setForm({...form,required:e.target.checked})} type="checkbox"/>Required</label><label className="checkbox-row"><input checked={form.sensitive} onChange={e=>setForm({...form,sensitive:e.target.checked})} type="checkbox"/>Sensitive field</label></div>{mutation.isError?<p className="form-error">{mutation.error instanceof Error?mutation.error.message:'The field could not be added.'}</p>:null}<div className="modal-actions"><button className="secondary-button" onClick={onClose} type="button">Cancel</button><button className="primary-action" type="submit">Add field</button></div></form></ModalDialog>
}

function EnvelopeModal({documents,policies,templates,onClose,onSaved}:{documents:HrDocumentWorkspace;policies:Array<{id:string;name:string;active:boolean}>;templates:DocumentStudioTemplate[];onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({documentId:'',templateVersionId:'',policyId:policies.find(item=>item.active)?.id??'',title:'',message:'Please review and complete this protected document.',expiresAt:'',employeeId:'',recipientRole:'employee',requiredAction:'sign'})
  const mutation=useMutation({mutationFn:createSignatureEnvelope,onSuccess:onSaved})
  const submit=(event:FormEvent)=>{event.preventDefault();mutation.mutate({documentId:form.documentId,templateVersionId:form.templateVersionId||null,policyId:form.policyId,title:form.title,message:form.message,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null,idempotencyKey:crypto.randomUUID(),recipients:[{employeeId:form.employeeId,recipientRole:form.recipientRole,requiredAction:form.requiredAction,routingOrder:1,authenticationTier:'standard'}]})}
  return <ModalDialog busy={mutation.isPending} busyLabel="Preparing signature envelope…" className="document-studio-modal" description="This creates a draft pinned to the current clean document version. Review the draft before sending." onClose={onClose} title="New signature envelope"><form className="document-studio-form" onSubmit={submit}><div className="form-grid"><label className="wide">Document<select onChange={e=>setForm({...form,documentId:e.target.value})} required value={form.documentId}><option value="">Choose a clean document</option>{documents.documents.filter(item=>item.version?.scanState==='clean').map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Policy<select onChange={e=>setForm({...form,policyId:e.target.value})} required value={form.policyId}><option value="">Choose a policy</option>{policies.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Template<select onChange={e=>setForm({...form,templateVersionId:e.target.value})} value={form.templateVersionId}><option value="">No placed fields</option>{templates.filter(item=>item.status==='published'&&item.currentVersionId).map(item=><option key={item.id} value={item.currentVersionId!}>{item.name}</option>)}</select></label><label className="wide">Envelope title<input onChange={e=>setForm({...form,title:e.target.value})} required value={form.title}/></label><label>Recipient<select onChange={e=>setForm({...form,employeeId:e.target.value})} required value={form.employeeId}><option value="">Choose an employee</option>{documents.employees.map(item=><option key={item.id} value={item.id}>{item.legalName}</option>)}</select></label><label>Required action<select onChange={e=>setForm({...form,requiredAction:e.target.value})} value={form.requiredAction}><option value="sign">Sign</option><option value="acknowledge">Acknowledge</option><option value="approve">Approve</option><option value="certify">Certify</option><option value="review">Review</option></select></label><label>Recipient role<input onChange={e=>setForm({...form,recipientRole:e.target.value})} required value={form.recipientRole}/></label><label>Expires<input onChange={e=>setForm({...form,expiresAt:e.target.value})} type="datetime-local" value={form.expiresAt}/></label><label className="wide">Message<textarea onChange={e=>setForm({...form,message:e.target.value})} rows={3} value={form.message}/></label></div>{mutation.isError?<p className="form-error">{mutation.error instanceof Error?mutation.error.message:'The envelope could not be created.'}</p>:null}<div className="modal-actions"><button className="secondary-button" onClick={onClose} type="button">Cancel</button><button className="primary-action" type="submit">Create draft envelope</button></div></form></ModalDialog>
}

function VoidEnvelopeModal({envelope,onClose,onSaved}:{envelope:DocumentStudioEnvelope;onClose:()=>void;onSaved:()=>void}){
  const [reason,setReason]=useState('')
  const mutation=useMutation({mutationFn:()=>voidSignatureEnvelope(envelope.id,reason),onSuccess:onSaved})
  return <ModalDialog busy={mutation.isPending} busyLabel="Voiding envelope…" className="document-studio-modal" description="The envelope and all remaining recipient actions will close. Existing audit evidence is preserved." onClose={onClose} title={`Void ${envelope.title}`}><form className="document-studio-form" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><label>Required reason<textarea autoFocus minLength={8} onChange={e=>setReason(e.target.value)} required rows={4} value={reason}/></label>{mutation.isError?<p className="form-error">{mutation.error instanceof Error?mutation.error.message:'The envelope could not be voided.'}</p>:null}<div className="modal-actions"><button className="secondary-button" onClick={onClose} type="button">Keep envelope</button><button className="primary-action danger" disabled={reason.trim().length<8} type="submit">Void envelope</button></div></form></ModalDialog>
}
