import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')

describe('shared SygSphere release guard', () => {
  it('keeps the handoff one-time, employee-bound, and MFA-backed', () => {
    const worker = read('worker/sharedIdentity.ts')
    const migration = read('supabase/migrations/20260908183000_shared_sygsphere_session_bridge.sql')
    const hardening = read('supabase/migrations/20260910010000_scope_shared_identity_to_sygsphere.sql')
    const browserSession = read('src/lib/sharedIdentitySession.ts')
    const callbackPage = read('src/pages/SharedIdentityCallbackPage.tsx')
    const supabase = read('src/lib/supabase.ts')
    expect(worker).toContain("const destination = '/sygsphere'")
    expect(worker).toContain("request.headers.get('origin') !== config.issuer")
    expect(worker).toContain("service_get_employee_login_email_target")
    expect(worker).toContain("service_issue_shared_identity_session")
    expect(worker).not.toContain('externalRole')
    expect(migration).toContain('launch_request_id uuid not null unique')
    expect(migration).toContain("account.auth_user_id = target_auth_user_id")
    expect(migration).toContain("employee.status = 'active'")
    expect(migration).toContain('or public.has_shared_identity_session()')
    expect(hardening).toContain('create or replace function public.has_mfa()')
    const globalMfaDefinition = hardening.match(/create or replace function public\.has_mfa\(\)[\s\S]*?\$\$;/)?.[0] ?? ''
    expect(globalMfaDefinition).not.toContain('has_shared_identity_session')
    expect(hardening).toContain('public.has_shared_identity_session()))')
    expect(hardening).toContain('if position(scoped_condition in function_definition) > 0 then')
    expect(hardening).toContain('elsif position(original_condition in function_definition) > 0 then')
    expect(browserSession).not.toContain('.setItem(')
    expect(browserSession).toContain('purgeLegacySharedIdentityStorage()')
    expect(supabase).toContain('storage: sharedIdentityAuthStorage')
    expect(supabase).toContain("storageKey: 'sygshift-shared-identity-memory-session'")
    expect(callbackPage).toContain('activateSharedIdentitySupabaseSession(')
    expect(callbackPage).not.toContain('getSupabaseClient().auth.setSession')
    expect(callbackPage).not.toContain('window.location.replace')
    expect(worker).toContain("const sessionCookie = '__Host-sygshift-shared-session'")
    expect(worker).toContain('accessToken: bootstrap.accessToken')
    expect(worker).toContain('refreshSupabaseSession(')
    expect(worker).toContain("const response = redirectResponse(callbackPath")
    expect(worker).toContain("`${config.supabaseUrl}/auth/v1/verify`")
    expect(worker).not.toContain('redirectResponse(actionLink')
    expect(migration).toContain('force row level security')
  })
})
