import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')

describe('shared SygShift release guard', () => {
  it('keeps both handoffs one-time, employee-bound, and scope-bound', () => {
    const worker = read('worker/sharedIdentity.ts')
    const migration = read('supabase/migrations/20260908183000_shared_sygsphere_session_bridge.sql')
    const hardening = read('supabase/migrations/20260910010000_scope_shared_identity_to_sygsphere.sql')
    const platformScope = read('supabase/migrations/20260910040000_scope_shared_identity_platform.sql')
    const merger = read('supabase/migrations/20260912010000_universal_sygilant_launch_access.sql')
    const guardProjection = read('supabase/migrations/20260912020000_guard_aal1_sygilant_permission_projection.sql')
    const browserSession = read('src/lib/sharedIdentitySession.ts')
    const callbackPage = read('src/pages/SharedIdentityCallbackPage.tsx')
    const supabase = read('src/lib/supabase.ts')
    expect(worker).toContain("'/': 'platform'")
    expect(worker).toContain("'/sygsphere': 'sygsphere'")
    expect(worker).toContain("return value === '/' || value === '/sygsphere'")
    expect(worker).toContain('readUnverifiedAssertionDestination(assertion) !== requestedDestination')
    expect(worker).toContain("request.headers.get('origin') !== config.issuer")
    expect(worker).toContain("service_get_employee_login_email_target")
    expect(worker).toContain("service_issue_shared_identity_session")
    expect(worker).not.toContain('externalRole')
    expect(migration).toContain('launch_request_id uuid not null unique')
    expect(migration).toContain("account.auth_user_id = target_auth_user_id")
    expect(migration).toContain("employee.status = 'active'")
    expect(migration).toContain('or public.has_shared_identity_session()')
    expect(hardening).toContain('create or replace function public.has_mfa()')
    const globalMfaDefinition = hardening.match(/create or replace function public\.has_mfa\(\)[\s\S]*?\$\$;/)?.[0] ?? ''
    expect(globalMfaDefinition).not.toContain('has_shared_identity_session')
    expect(hardening).toContain('public.has_shared_identity_session()))')
    expect(hardening).toContain('if position(scoped_condition in function_definition) > 0 then')
    expect(hardening).toContain('elsif position(original_condition in function_definition) > 0 then')
    expect(platformScope).toContain("check (scope in ('platform', 'sygsphere'))")
    expect(platformScope).toContain("'apps.sygshift.access'")
    expect(platformScope).toContain("where access_role.code = 'system_admin'")
    expect(platformScope).toContain("public.has_scoped_shared_identity_session('platform')")
    expect(platformScope).toContain("shared_session.scope = target_scope")
    expect(platformScope).toContain("'scope', target_scope")
    expect(platformScope).toContain("'sygsphere',\n    target_request_id")
    const platformMfaDefinition = platformScope.match(/create or replace function public\.has_mfa\(\)[\s\S]*?\$\$;/)?.[0] ?? ''
    expect(platformMfaDefinition).toContain("has_scoped_shared_identity_session('platform')")
    expect(platformMfaDefinition).not.toContain("has_scoped_shared_identity_session('sygsphere')")
    expect(browserSession).not.toContain('.setItem(')
    expect(browserSession).toContain('purgeLegacySharedIdentityStorage()')
    expect(supabase).toContain('storage: sharedIdentityAuthStorage')
    expect(supabase).toContain("storageKey: 'sygshift-shared-identity-memory-session'")
    expect(callbackPage).toContain('activateSharedIdentitySupabaseSession(')
    expect(callbackPage).toContain("payload.scope === expectedScope")
    expect(callbackPage).not.toContain('getSupabaseClient().auth.setSession')
    expect(callbackPage).not.toContain('window.location.replace')
    expect(worker).toContain("const sessionCookie = '__Host-sygshift-shared-session'")
    expect(worker).toContain('accessToken: bootstrap.accessToken')
    expect(worker).toContain('refreshSupabaseSession(')
    expect(worker).toContain("const response = redirectResponse(callbackPath")
    expect(worker).toContain("`${config.supabaseUrl}/auth/v1/verify`")
    expect(worker).not.toContain('redirectResponse(actionLink')
    expect(worker).toContain('target_scope: scope')
    expect(worker).toContain('scope,\n    sharedIdentityToken')
    expect(worker).not.toContain('/api/v1/auth/shared-identity/session/sync')
    expect(worker).toContain("claims.session_id !== shared.authSessionId")
    expect(worker).toContain('verifySharedSession(shared.sessionToken, token, scope, config)')
    expect(supabase).toContain('autoRefreshToken: false')
    expect(supabase).not.toContain('TOKEN_REFRESHED')
    expect(supabase).not.toContain('syncSharedIdentityServerSession')
    expect(migration).toContain('force row level security')
    expect(merger).toContain("shared_session.assurance_level in ('aal2', 'security_key', 'trusted_device', 'external_mfa')")
    expect(merger).toContain("target_assurance_level not in ('aal1', 'aal2', 'security_key', 'trusted_device', 'external_mfa')")
    expect(merger).toContain('private.shared_identity_session_assurance_allowed(employee.id, target_assurance_level)')
    expect(merger).toContain("private.has_high_assurance_shared_identity_session('platform')")
    expect(guardProjection).toContain("permission_code = 'apps.sygilant.access'")
    expect(guardProjection).toContain("employee.role = 'guard'")
    expect(guardProjection).toContain('not private.employee_requires_mfa(employee.id)')
    expect(guardProjection).toContain('private.employee_effective_permissions(actor.employee_id)')
    expect(guardProjection).toContain('not catalog.requires_mfa')
    expect(guardProjection).toContain('or public.has_mfa()')
    expect(worker).toContain("identity.assuranceLevel === 'aal1' && identity.roleId !== 'guard'")
    expect(worker).toContain("local.role === 'guard' && local.requiresMfa === false")
    expect(worker).toContain('roleId: identity.roleId')
    expect(worker).toContain('roleId: ticket.roleId')
    expect(worker).toContain('local.role !== identity.roleId')
    expect(worker).toContain('local.role !== ticket.roleId')
    expect(worker).toContain("value.assuranceLevel !== 'aal1' || value.roleId === 'guard'")
  })
})
