/// <reference types="node" />

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const migration = readFileSync(join(root, 'supabase', 'migrations', '20260908233000_sygsphere_experience_mentions_previews.sql'), 'utf8')
const immediateAvailabilityMigration = readFileSync(join(root, 'supabase', 'migrations', '20260930215000_document_upload_immediate_availability.sql'), 'utf8')
const mentionMatcherRepair = readFileSync(join(root, 'supabase', 'migrations', '20260912050000_repair_sygsphere_mention_token_matcher.sql'), 'utf8')
const data = readFileSync(join(root, 'src', 'data', 'sygsphere.ts'), 'utf8')
const page = readFileSync(join(root, 'src', 'pages', 'SygSpherePage.tsx'), 'utf8')
const files = readFileSync(join(root, 'worker', 'sygsphereFiles.ts'), 'utf8')
const worker = readFileSync(join(root, 'worker', 'index.ts'), 'utf8')

describe('SygSphere experience boundaries', () => {
  it('matches human-name mentions literally without executing employee names as regular expressions', () => {
    expect(mentionMatcherRepair).toContain('strpos(substring(normalized_body from search_from), mention_token)')
    expect(mentionMatcherRepair).toContain("'Please ask @A+B [Ops]!', 'A+B [Ops]'")
    expect(mentionMatcherRepair).not.toMatch(/regexp_replace\s*\(\s*lower\s*\(\s*target_label/i)
  })

  it('stores structured mentions and validates every target against active conversation membership', () => {
    expect(migration).toContain('create table private.sygsphere_mentions')
    expect(migration).toContain('member.conversation_id = new.conversation_id')
    expect(migration).toContain("member.removed_at is null and employee.status = 'active' and account.disabled_at is null")
    expect(migration).toContain("action = 'mentions'")
    expect(data).toContain('mentionIds: sphereMentionIds')
    expect(data).toContain('Promise.allSettled([spherePeople')
    expect(data).toContain("sphereRequest('conversation', { conversationId })")
    expect(page).toContain('sphere-mention--self')
  })

  it('keeps profile photos private while allowing security-complete SygSphere accounts to render fallbacks', () => {
    expect(migration).toContain('public.sygsphere_can_read_avatar(name)')
    expect(migration).toContain("session_context->>'must_change_password'")
    expect(migration).toContain("session_context->>'mfa_required'")
    expect(data).toContain("storage.from('employee-photos').download(photoPath)")
    expect(page).toContain('url ? <img')
  })

  it('previews only approved image, PDF, and bounded plain-text content behind membership authorization', () => {
    expect(files).toContain("dependencies.authorize('access'")
    expect(files).toContain("url.searchParams.get('mode') === 'preview'")
    expect(files).toContain("'content-security-policy': \"sandbox; default-src 'none'")
    expect(files).toContain("'cross-origin-resource-policy': 'same-origin'")
    expect(data).toContain("file.mimeType === 'text/plain' && file.sizeBytes <= 1048576")
    expect(page).toContain("import { SecurePdfViewer } from '../components/SecurePdfViewer'")
    expect(page).toContain('<SecurePdfViewer title={file.filename} url={preview.data.url} />')
    expect(page).not.toContain('<iframe src={preview.data.url}')
  })

  it('makes supported attachments available after protected storage and checksum verification', () => {
    expect(migration).toContain('enabled boolean not null default true')
    expect(migration).toContain('inline_max_bytes integer not null default 26214400 check (inline_max_bytes = 26214400)')
    expect(migration).toContain('resumable_max_bytes integer not null default 104857600 check (resumable_max_bytes = 104857600)')
    expect(migration).toContain('Larger resumable SygSphere uploads are not enabled.')
    expect(migration).toContain("lower(trim(coalesce(input->>'mimeType',''))) not in ('image/jpeg','image/png','image/webp')")
    expect(immediateAvailabilityMigration).toContain("if auth.role() is distinct from 'service_role' then raise insufficient_privilege")
    expect(immediateAvailabilityMigration).toContain('where conversation_id = cid and employee_id = target_actor_id and removed_at is null')
    expect(immediateAvailabilityMigration).toContain("'The stored file does not match the approved upload.'")
    expect(immediateAvailabilityMigration).toContain("'checksum-verified'")
    expect(immediateAvailabilityMigration).toContain('service_complete_sygsphere_resumable_upload_available')
    expect(immediateAvailabilityMigration).toContain("'A SHA-256 checksum is required.'")
    expect(immediateAvailabilityMigration).toContain('grant execute on function public.service_complete_sygsphere_resumable_upload_available')
    expect(data).toContain('sphereResumableMaxBytes = 104857600')
    expect(data).toContain('sphereStandardUploadMaxBytes = 6 * 1024 * 1024')
    expect(data).toContain('sphereStorageConfirmationDelaysMs = [0, 250]')
    expect(data).toContain('sphereCompleteUpload')
    expect(data).not.toContain('sphereUploadStatus')
    expect(page).not.toContain('SphereUploadRecovery')
    expect(data).toContain('new Upload(file')
    expect(data).toContain('fingerprint: async () => `sygsphere:')
    expect(data).toContain("code: 'sygsphere_storage_transfer_failed'")
    expect(data).toContain('completionPending: false')
    expect(page).toContain('refetchInterval: 30000')
    expect(files).toContain('const limit = 26214400')
    expect(files).toContain("dependencies.authorize('authorize'")
    expect(files).toContain("crypto.subtle.digest('SHA-256'")
    expect(files).toContain('await dependencies.store')
    expect(files).toContain('await verifyStoredSphereFile(')
    expect(files).toContain('await dependencies.fetch(objectKey)')
    expect(files).toContain('The stored file size does not match the approved upload.')
    expect(files).toContain('The stored file checksum does not match the approved upload.')
    expect(files).toContain("state: 'clean'")
    expect(files).not.toContain('dependencies.scan')
    expect(worker).toContain('recoverStoredSygSphereFiles')
    expect(worker).toContain('recoverStoredSygSphereResumableUploads')
    expect(worker).toContain('privateStorageChecksum')
    expect(worker).toContain("'service_complete_sygsphere_resumable_upload_available'")
    expect(worker).toContain("state: 'prepared'")
    expect(worker).not.toContain('/retry')
    expect(worker).toContain('if (checksum !== expectedChecksum)')
    expect(immediateAvailabilityMigration).not.toContain('scanner =')
    expect(immediateAvailabilityMigration).not.toContain('scanned_at =')
  })
})
